# Markdownlint configuration
default: true

# Allow inline HTML
MD033: false

# Allow trailing punctuation in headers
MD026: false

# Allow multiple spaces after blockquote marker
MD027: false

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Allow duplicate headers
MD024:
  siblings_only: true